import { Factory, Seeder } from 'typeorm-seeding'
import { Connection } from 'typeorm'
import { Book } from '../entity/book.entity'
 
export default class CreateBooks implements Seeder {

  public async run(factory: Factory, connection: Connection): Promise<any> {

    const assetBaseUrl = "127.0.0.1:3000/api/v1/images"
    
    await connection
      .createQueryBuilder()
      .insert()
      .into(Book)
      .values([
        {
            author: 'Michelle Obama',
            title: 'Becoming',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/becoming-cover_suqk9r.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 23,
            price: 10,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Elizabeth Gilbert',
            title: 'Big Magic',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/big-magic-cover_euc3rh.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 23,
            price: 10,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'W. Chan Kim',
            title: 'Blue Ocean Strategy',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/blue-ocean-strategy_amjdl6.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 30,
            price: 15,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Jim Collins',
            title: 'Built to Last',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/built-to-last-cover_cb92oa.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 30,
            price: 15,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Bret Slatkin',
            title: 'Effective Python',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/effective-python-cover_s7dahh.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 10,
            price: 10,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Howard Slatkin',
            title: 'Fifth Avenue Style',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/fifth-avenue-style_wknvht.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 10,
            price: 10,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Jennifer L. Amentrout',
            title: 'From Blood and Ash',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/from-blood-and-ash_hs4leq.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 10,
            price: 10,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Ben Horowitz',
            title: 'The Hard Thing About Hard Things',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/hard-things-about-hard-things_g0frrg.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 12,
            price: 5,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Don Miguel Ruiz',
            title: 'La Voz Del Conocimiento',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/la-voz-del-conocimiento_j5mkty.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 12,
            price: 5,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Oyinka Braithwaite',
            title: 'My sister, the serial Killer',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/my-sister-serial-killer_asapyi.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 12,
            price: 5,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Jennifer L. Amentrout',
            title: 'Obsidian',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/obsidian_nojlw9.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 12,
            price: 5,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Elizabeth Gilbert',
            title: 'The Signature of all things',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/signature-of-all-things_ogxgi7.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 12,
            price: 10,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Edmond Lau',
            title: 'The Effective Engineer',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/the-effective-engineer-cover_bgj7u4.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 23,
            price: 25,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Don Miguel Ruiz',
            title: 'The Four Arguments',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/the-four-agreements_gtp2bw.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 23,
            price: 25,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Clayton Christensen',
            title: "The Innovator's dilemma",
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/the-innovators-dilemma_ap1zo4.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 23,
            price: 25,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Eric Ries',
            title: 'The Lean Startup',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/the-lean-startup-cover_dmwrjj.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 23,
            price: 25,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Eric Ries',
            title: 'The Startup Way',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/the-startup-way_znfqbe.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 50,
            price: 25,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Oyinkan Braithwaite',
            title: 'Treasure',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/treasure_lccloa.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 50,
            price: 10,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'Ben Horowitz',
            title: 'What you do is who you are',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/what-you-do_rerozi.jpg`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 50,
            price: 10,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            author: 'One Author',
            title: 'How to win friends',
            description: 'This is a self motivating book',
            body: 'The story witin starts from the migration of Etugrul from Anatolia to Instabul which is modern day Turkey',
            imgUrl: `${assetBaseUrl}/how-to-win-friends_t1a2jn.webp`,
            authoredYear: '2016',
            publisher: 'Bashtem',
            releaseDate: '2016',
            quantity: 50,
            price: 10,
            featured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
      ])
      .execute()
  }
}